In [2]:
#broadcasting in numpy  
import numpy as np
arr1=np.random.randint(1,88,size=(3,3))
print("Original Array:", arr1)
arr2=np.random.randint(1,88,size=(3,))
print("Array to be broadcasted:", arr2)

result=arr1+arr2
print("Result of broadcasting:", result)


Original Array: [[85 54 86]
 [45  4 73]
 [76 21 43]]
Array to be broadcasted: [13  8 54]
Result of broadcasting: [[ 98  62 140]
 [ 58  12 127]
 [ 89  29  97]]


In [3]:
#linear algebra in numpy
arr3=np.random.randint(1,99,size=(3,3))
print("Original Array:", arr3)
determined_array=np.linalg.det(arr3)
print("Determinant of the array:", determined_array)
inverse_array=np.linalg.inv(arr3)
print("Inverse of the array:", inverse_array)
eigenvalues,eigenvectors=np.linalg.eig(arr3)
print("Eigenvalues of the array:", eigenvalues)

Original Array: [[37 97 67]
 [93 88 23]
 [83 11 86]]
Determinant of the array: -740804.9999999988
Inverse of the array: [[-0.00987439  0.01026586  0.00494732]
 [ 0.00821944  0.00321137 -0.00726237]
 [ 0.00847861 -0.0103185   0.00778207]]
Eigenvalues of the array: [-54.41575066 195.93431652  69.48143415]


In [4]:
#masked array in numpy
arr4=np.random.randint(1,99,size=(3,3))
print("Original Array:", arr4)
masked_array=np.ma.masked_array(arr4,mask=[[0,1,0],[1,0,1],[0,1,0]])
print("Masked Array:", masked_array)

Original Array: [[17  3 75]
 [ 2 38 98]
 [36 35 69]]
Masked Array: [[17 -- 75]
 [-- 38 --]
 [36 -- 69]]
