In [1]:
#practice numpy
!pip install numpy

ERROR: Could not find a version that satisfies the requirement numpy (from versions: none)
ERROR: No matching distribution found for numpy


In [2]:
!pip install numpy pandas

  Using cached pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 6.2 MB/s  0:00:00 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 11.3 MB/s  0:00:00eta 0:00:01
Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pandas]2m3/4 [pandas]


In [7]:
#practice numpy
import numpy as np
array1 = np.random.randint(1,10,size=(3,3))
print("Original Array:", array1)
#replace all the values greater than 5 with 0
array1[array1 > 5] = 0
#replace all the in 1 coulumns with 5
array1[:, 0] = 5
print("Array with first column replaced:", array1)  
#replace the daigonal values with 1
np.fill_diagonal(array1,1)
print("Array with diagonal values replaced:", array1)
#replace the values in the last row with 9
array1[-1, :] = 9
print("Array with last row replaced:", array1)



Original Array: [[9 2 6]
 [3 1 5]
 [9 7 9]]
Array with first column replaced: [[5 2 0]
 [5 1 5]
 [5 0 0]]
Array with diagonal values replaced: [[1 2 0]
 [5 1 5]
 [5 0 1]]
Array with last row replaced: [[1 2 0]
 [5 1 5]
 [9 9 9]]


In [9]:
#slicing the array
array1=np.arange(1,10).reshape(3,3)
print("Original Array:", array1)

#sub_array that contain element from 2 nd row and 2nd column
sub_array = array1[0:2, 0:2]
print("Sub-array:", sub_array)

Original Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub-array: [[1 2]
 [4 5]]


In [13]:
#extract elements from the border
array1 = np.arange(1,26).reshape(5,5)
print("Original Array:", array1)
border_elements=np.concatenate((array1[0,:],array1[-1,:],array1[1:-1,0],array1[1:-1,-1]))
print("Border Elements:", border_elements)

Original Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Border Elements: [ 1  2  3  4  5 21 22 23 24 25  6 11 16 10 15 20]


In [23]:
#operation of two arrays
arr1=np.random.randint(1,10,size=(3,3))
arr2=np.random.randint(1,10,size=(3,3))
print("Array 1:", arr1)
print("Array 2:", arr2)
sum_array=arr1+arr2
print("Sum of two arrays:", sum_array)  
difference_array=arr1-arr2
print("Difference of two arrays:", difference_array)    
product_array=arr1*arr2
print("Product of two arrays:", product_array)
division_array=arr1/arr2
print("Division of two arrays:", division_array)


#row and cloumn wise sum
row_sum=np.sum(arr1, axis=1)
print("Row-wise sum:", row_sum )
column_sum=np.sum(arr1, axis=0) 
print("Column-wise sum:", column_sum)


Array 1: [[6 7 7]
 [8 3 2]
 [9 2 4]]
Array 2: [[8 4 9]
 [8 8 9]
 [3 2 6]]
Sum of two arrays: [[14 11 16]
 [16 11 11]
 [12  4 10]]
Difference of two arrays: [[-2  3 -2]
 [ 0 -5 -7]
 [ 6  0 -2]]
Product of two arrays: [[48 28 63]
 [64 24 18]
 [27  4 24]]
Division of two arrays: [[0.75       1.75       0.77777778]
 [1.         0.375      0.22222222]
 [3.         1.         0.66666667]]
Row-wise sum: [20 13 15]
Column-wise sum: [23 12 13]


In [26]:
#statistical operations
from array import array


mean_value=np.mean(arr1)
print("Mean value:", mean_value)
median_value=np.median(arr1)
print("Median value:", median_value)
variance_value=np.var(arr1)
print("Variance value:", variance_value)
standard_deviation_value=np.std(arr1)
print("Standard Deviation value:", standard_deviation_value)   


normalized_array=(arr1-mean_value)/standard_deviation_value
print("Normalized Array:", normalized_array)

Mean value: 5.333333333333333
Median value: 6.0
Variance value: 6.222222222222222
Standard Deviation value: 2.494438257849294
Normalized Array: [[ 0.26726124  0.6681531   0.6681531 ]
 [ 1.06904497 -0.93541435 -1.33630621]
 [ 1.46993683 -1.33630621 -0.53452248]]
